from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class AppendStaffWindow(QtWidgets.QWidget):
    def __init__(self, db, rest):
        super().__init__()
        self.setupUi(rest)
        self.db = db

    def setupUi(self, rest):
        self.setObjectName("Form")
        self.setFixedSize(461, 674)
        self.setStyleSheet("background-color: rgb(49, 51, 56);")
        self.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        self.enter_btn = QtWidgets.QPushButton(parent=self)
        self.enter_btn.setEnabled(True)
        self.enter_btn.setGeometry(QtCore.QRect(150, 620, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.enter_btn.setFont(font)
        self.enter_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.enter_btn.setStyleSheet("background-color: rgb(99, 97, 235);\n"
"color: rgb(222, 221, 218);")
        self.enter_btn.setObjectName("enter_btn")
        self.position_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.position_lineEdit.setGeometry(QtCore.QRect(20, 510, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.position_lineEdit.setFont(font)
        self.position_lineEdit.setStyleSheet("color: rgb(246, 245, 244);\n"
"background-color: #1e1f22;\n"
"border: none;")
        self.position_lineEdit.setObjectName("position_lineEdit")
        self.role_lbl = QtWidgets.QLabel(parent=self)
        self.role_lbl.setGeometry(QtCore.QRect(40, 550, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.role_lbl.setFont(font)
        self.role_lbl.setStyleSheet("color: rgb(222, 221, 218);")
        self.role_lbl.setObjectName("role_lbl")
        self.secondname_lbl = QtWidgets.QLabel(parent=self)
        self.secondname_lbl.setGeometry(QtCore.QRect(30, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.secondname_lbl.setFont(font)
        self.secondname_lbl.setStyleSheet("color: rgb(222, 221, 218);")
        self.secondname_lbl.setObjectName("secondname_lbl")
        self.position_lbl = QtWidgets.QLabel(parent=self)
        self.position_lbl.setGeometry(QtCore.QRect(30, 470, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.position_lbl.setFont(font)
        self.position_lbl.setStyleSheet("color: rgb(222, 221, 218);")
        self.position_lbl.setObjectName("position_lbl")
        self.title_lbl = QtWidgets.QLabel(parent=self)
        self.title_lbl.setGeometry(QtCore.QRect(70, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        self.title_lbl.setFont(font)
        self.title_lbl.setStyleSheet("color: rgb(246, 245, 244);")
        self.title_lbl.setObjectName("title_lbl")
        self.secondname_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.secondname_lineEdit.setGeometry(QtCore.QRect(20, 190, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.secondname_lineEdit.setFont(font)
        self.secondname_lineEdit.setStyleSheet("color: rgb(246, 245, 244);\n"
"background-color: #1e1f22;\n"
"border: none;")
        self.secondname_lineEdit.setObjectName("secondname_lineEdit")
        self.name_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.name_lineEdit.setGeometry(QtCore.QRect(20, 110, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.name_lineEdit.setFont(font)
        self.name_lineEdit.setStyleSheet("color: rgb(246, 245, 244);\n"
"background-color: #1e1f22;\n"
"border: none;")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.comboBox = QtWidgets.QComboBox(parent=self)
        self.comboBox.setGeometry(QtCore.QRect(240, 550, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("color: rgb(184, 184, 184);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.name_lbl = QtWidgets.QLabel(parent=self)
        self.name_lbl.setGeometry(QtCore.QRect(30, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.name_lbl.setFont(font)
        self.name_lbl.setStyleSheet("color: rgb(222, 221, 218);")
        self.name_lbl.setObjectName("name_lbl")
        self.thirdname_lbl = QtWidgets.QLabel(parent=self)
        self.thirdname_lbl.setGeometry(QtCore.QRect(30, 230, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.thirdname_lbl.setFont(font)
        self.thirdname_lbl.setStyleSheet("color: rgb(222, 221, 218);")
        self.thirdname_lbl.setObjectName("thirdname_lbl")
        self.thirdname_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.thirdname_lineEdit.setGeometry(QtCore.QRect(20, 270, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.thirdname_lineEdit.setFont(font)
        self.thirdname_lineEdit.setStyleSheet("color: rgb(246, 245, 244);\n"
"background-color: #1e1f22;\n"
"border: none;")
        self.thirdname_lineEdit.setObjectName("thirdname_lineEdit")
        self.login_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.login_lineEdit.setGeometry(QtCore.QRect(20, 350, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.login_lineEdit.setFont(font)
        self.login_lineEdit.setStyleSheet("color: rgb(246, 245, 244);\n"
"background-color: #1e1f22;\n"
"border: none;")
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.login_lbl = QtWidgets.QLabel(parent=self)
        self.login_lbl.setGeometry(QtCore.QRect(30, 310, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.login_lbl.setFont(font)
        self.login_lbl.setStyleSheet("color: rgb(222, 221, 218);")
        self.login_lbl.setObjectName("login_lbl")
        self.password_lineEdit = QtWidgets.QLineEdit(parent=self)
        self.password_lineEdit.setGeometry(QtCore.QRect(20, 430, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("color: rgb(246, 245, 244);\n"
"background-color: #1e1f22;\n"
"border: none;")
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.password_lbl = QtWidgets.QLabel(parent=self)
        self.password_lbl.setGeometry(QtCore.QRect(30, 390, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.password_lbl.setFont(font)
        self.password_lbl.setStyleSheet("color: rgb(222, 221, 218);")
        self.password_lbl.setObjectName("password_lbl")
        self.enter_btn.clicked.connect(lambda: self.enter_clicked(rest))

        self.retranslateUi()
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Добавить сотрудника"))
        self.enter_btn.setText(_translate("Form", "Добавить"))
        #self.position_lineEdit.setText(_translate("Form", "Должность"))
        self.role_lbl.setText(_translate("Form", "Роль"))
        self.secondname_lbl.setText(_translate("Form", "Фамилия"))
        #self.position_lbl.setText(_translate("Form", "Должность"))
        self.title_lbl.setText(_translate("Form", "Добавить сотрудника"))
        self.secondname_lineEdit.setText(_translate("Form", "Фамилия"))
        self.name_lineEdit.setText(_translate("Form", "Имя"))
        self.comboBox.setItemText(0, _translate("Form", "Администратор"))
        self.comboBox.setItemText(1, _translate("Form", "Сотрудник"))
        self.name_lbl.setText(_translate("Form", "Имя"))
        self.thirdname_lbl.setText(_translate("Form", "Отчество"))
        self.thirdname_lineEdit.setText(_translate("Form", "Отчество"))
        self.login_lineEdit.setText(_translate("Form", "Логин"))
        self.login_lbl.setText(_translate("Form", "Логин"))
        self.password_lineEdit.setText(_translate("Form", "Пароль"))
        self.password_lbl.setText(_translate("Form", "Пароль"))

    def enter_clicked(self, rest):
        role = 2
        if self.comboBox.currentIndex() == 0:
                role = 1
        else:
                role = 2
        #self.db.appendStaff(self.name_lineEdit.text(), self.secondname_lineEdit.text(), self.thirdname_lineEdit.text(), self.position_lineEdit.text(), role, self.login_lineEdit.text(), self. password_lineEdit.text())
        self.db.appendStaff(self.name_lineEdit.text(), self.secondname_lineEdit.text(), self.thirdname_lineEdit.text(), role, self.login_lineEdit.text(), self. password_lineEdit.text())
        rest()
        self.close()

if __name__ =="__main__":
    app = QtWidgets.QApplication(sys.argv)
    editProfile_Window = AppendStaffWindow()
    editProfile_Window.show()
    app.exec()
